### ISSUE TITLE
RaytraceAntiXray not hiding all ores during chunk loading using SDK

### ISSUE THREAD

**Issue by AebSISH646** [Imanity-Software/raytrace-antixray-git#28]
### Expected behavior

All ores should be properly hidden during chunk loading when using the RaytraceAntiXray SDK, as they are when using only the plugin without the SDK.

### Observed/Actual behavior

Some appear visible during chunk loading, even though they should be hidden. This happens inconsistently but is noticeable.

### Steps/models to reproduce

1. Run Leaf 1.21.4 with the RaytraceAntiXray SDK patch applied
2. Observe chunk loading — some ores may appear when they shouldn't
3. Repeat the same setup without applying the SDK (plugin-only) — ores are hidden as expected

### Plugin list

- RaytraceAntiXray

### RaytraceAntiXray version

0.18.3beta

### Spigot version & fork name

- Leaf 1.21.4 + SDK patch
- A custom Paper fork with the SDK patch (applied exactly as per instructions)

### Agreements

- [x] I am running the latest version of Raytrace AntiXray available.
- [x] I have searched for and ensured there isn't already an open issue regarding this.

### Other

The SDK loads properly — confirmed by console output.
Let me know if you'd like logs, video evidence, or additional configuration details.

**Comment by LeeGodSRC** [comment]
Should be fixed in 0.18.4beta!

**Comment by AebSISH646** [comment]
Thanks for the quick update!

I just tested version 0.18.4beta on Leaf 1.21.4 with the default configuration, and unfortunately the issue still persists. Some ores are still visible during chunk loading — the anti-xray doesn’t consistently hide them.

To clarify: I understand that ores on the surface (above Y=65) are visible by default, which is expected. The issue is with some underground ores (below Y=65) that still appear during chunk loading, even though they should be hidden.

For reference, I'm using freecam to observe the chunk loading behavior. Additionally, there are cases where ores remain completely visible, even though they are fully surrounded by stone or other blocks — they’re not adjacent to air, water, or lava, so they shouldn't be exposed under normal conditions.

https://github.com/user-attachments/assets/65a21722-9cb2-4458-8f64-9724a0243bbc

Let me know if there's anything specific you'd like me to test or share (logs, config).

**Comment by LeeGodSRC** [comment]
Well thanks for your detailed report! It's a little tricky as we currently treat every block changes (called from SDK) will trigger a block reveal update in 2 block radius and from what I can tell from the footage it may be the cause. Can you perhaps check if all of those revealed ores are close to waters? and if you change blockUpdateRadius to 1 fixes the issue?

**Comment by AebSISH646** [comment]
Thanks for the clarification!

I just tested it with blockUpdateRadius set to 1, and that does fix the issue — ores are now properly hidden during chunk loading.

Also, you're right — while I initially thought some of the ores were completely surrounded, after double-checking, I noticed that there was always some kind of liquid (water or lava) nearby, usually within the 2-block radius. So that seems to explain the reveal behavior.

**Comment by AebSISH646** [comment]
When will this issue be fixed? Some ores are still visible because of it, and we’ll soon need a fully functional plugin for the server launch. Setting the blockUpdateRadius to 1 helps, but unfortunately, when water spills onto ores in a newly loaded chunk, they become visible again.

**Comment by LeeGodSRC** [comment]
I can't really think of a way to efficiently fix the issue at the moment, I think with blockUpdateRadius the issue should be much less noticeable and adapt with fake ores should make it essentially impossible to recognize
